# build_dictionaries.py — Corrected
# Previously: generated keys from numeric column values (sectional area, wpm numbers)
#             producing garbage keys like "山形鋼_0.044305" instead of "山形鋼_50x50x6"
# Fixed:      uses col0 (spec string) + col1 (material/shape name) as the lookup key,
#             col3 (weight per meter, kg/m) as the value — confirmed from Excel analysis.

import json
import re
import math


def normalize(text):
    if not text:
        return ""
    t = str(text).strip()
    t = t.replace('●', '')
    t = t.replace('Φ', 'phi').replace('φ', 'phi')
    t = t.replace('□', 'sq')
    t = t.replace('×', 'x').replace('*', 'x')
    t = t.replace(' ', '').lower()
    if t.startswith('l-'):
        t = t[2:]

    def repl(m):
        val = m.group(0)
        try:
            f = float(val)
            if f == int(f):
                return str(int(f))
            return str(f)
        except:
            return val

    t = re.sub(r'(\d+\.\d+)', repl, t)
    return t


def is_numeric(s):
    if s is None:
        return False
    st = str(s).strip()
    if not st or st.lower() in ('nan', ''):
        return False
    try:
        f = float(st)
        return not math.isnan(f)
    except:
        return False


SKIP_LABELS = {
    '', 'nan', 'steel shapes', 'size', 'specification', 'sectional area',
    '(cm2)', 'material specification', 'no.13,14',
}

DATA_PATH = r'd:\RAYSAN\KMTI Data Management\Systems\kmti_workstation_v3_new\src\data\raw_materials_all.json'
TS_OUT    = r'd:\RAYSAN\KMTI Data Management\Systems\kmti_workstation_v3_new\src\data\shape_lookup.ts'
JSON_OUT  = r'd:\RAYSAN\KMTI Data Management\Systems\kmti_workstation_v3_new\src\data\shape_lookup.json'

with open(DATA_PATH, encoding='utf-8') as f:
    data = json.load(f)

shapes = {}
skipped = 0

for row in data:
    if not row or len(row) < 4:
        skipped += 1
        continue

    spec    = str(row[0]).strip()
    mat     = str(row[1]).strip()
    wpm_raw = row[2]   # col2 = unit weight in kg/cm — multiply by 100 for kg/m

    # Skip header/label rows
    if normalize(spec) in SKIP_LABELS or normalize(mat) in SKIP_LABELS:
        skipped += 1
        continue

    # Skip if spec is a bare number (not a real dimension string)
    try:
        float(spec)
        skipped += 1
        continue
    except:
        pass

    if not is_numeric(wpm_raw):
        skipped += 1
        continue

    wpm = float(wpm_raw) * 100.0  # kg/cm -> kg/m
    if wpm <= 0:
        skipped += 1
        continue

    norm_mat  = normalize(mat)
    norm_spec = normalize(spec)

    if not norm_mat or not norm_spec:
        skipped += 1
        continue

    # Primary key: material_spec  (e.g. "ss400_50x50x6", "stkr400_175x175x9")
    shapes[f"{norm_mat}_{norm_spec}"] = wpm

    # Fallback key: spec-only (e.g. "50x50x6")
    # First occurrence wins — avoids overwriting with a different-material same-spec entry
    if norm_spec not in shapes:
        shapes[norm_spec] = wpm

print(f"Built {len(shapes)} keys ({skipped} rows skipped)")

# Write TypeScript
with open(TS_OUT, 'w', encoding='utf-8') as f:
    f.write("// AUTO-GENERATED by build_dictionaries.py\n")
    f.write("// Key format: '<material>_<spec>' or '<spec>' (spec-only fallback)\n")
    f.write("// Value: weight per meter (kg/m) from KMTI Raw Material Calculator.xlsx\n")
    f.write("export const shapeLookup: Record<string, number> = ")
    f.write(json.dumps(shapes, ensure_ascii=False))
    f.write(";\n")

# Write JSON for inspection/testing
with open(JSON_OUT, 'w', encoding='utf-8') as f:
    json.dump(shapes, f, ensure_ascii=False, indent=2)

print(f"Written: {TS_OUT}")
print(f"Written: {JSON_OUT}")
