"""initial

Revision ID: 2d1f2d3f8227
Revises: 
Create Date: 2026-07-20 07:38:59.944181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d1f2d3f8227'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('w_account')
    op.drop_table('tbl_wordchar')
    op.drop_index(op.f('ix_kmti_user_signatures_name'), table_name='kmti_user_signatures')
    op.drop_table('kmti_user_signatures')
    op.drop_index(op.f('ix_kmti_workstation_notes_workstation_ip'), table_name='kmti_workstation_notes')
    op.drop_table('kmti_workstation_notes')
    op.drop_index(op.f('ix_work_schedule_notifications_component_id'), table_name='work_schedule_notifications')
    op.drop_index(op.f('ix_work_schedule_notifications_id'), table_name='work_schedule_notifications')
    op.drop_index(op.f('ix_work_schedule_notifications_job_id'), table_name='work_schedule_notifications')
    op.drop_index(op.f('ix_work_schedule_notifications_member_name'), table_name='work_schedule_notifications')
    op.drop_table('work_schedule_notifications')
    op.drop_table('kmti_feedback')
    op.drop_table('tblfile')
    op.drop_table('tbl_useracc')
    op.alter_column('cad_file_index', 'content_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ft_search'), table_name='cad_file_index', mysql_prefix='FULLTEXT')
    op.drop_index(op.f('idx_filepath'), table_name='cad_file_index', mysql_length={'file_path': 255})
    op.drop_index(op.f('idx_project_folder_type'), table_name='cad_file_index')
    op.drop_index(op.f('idx_project_parent'), table_name='cad_file_index', mysql_length={'parent_path': 255})
    op.drop_index(op.f('idx_project_path'), table_name='cad_file_index', mysql_length={'file_path': 255})
    op.create_index(op.f('ix_cad_file_index_file_path'), 'cad_file_index', ['file_path'], unique=False)
    op.create_index(op.f('ix_cad_file_index_parent_path'), 'cad_file_index', ['parent_path'], unique=False)
    op.drop_index(op.f('idx_eng_char'), table_name='char_search', mysql_length={'eng_char': 255})
    op.drop_index(op.f('idx_jp_char'), table_name='char_search', mysql_length={'jp_char': 255})
    op.create_index(op.f('ix_char_search_id'), 'char_search', ['id'], unique=False)
    op.drop_index(op.f('idx_dg_eng'), table_name='designers')
    op.alter_column('heat_trmnt', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('heat_trmnt', 'eng_char',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('heat_trmnt', 'jp_char',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.String(length=255),
               nullable=True)
    op.drop_index(op.f('idx_ht_category'), table_name='heat_trmnt', mysql_length={'category': 191})
    op.drop_index(op.f('idx_ht_eng'), table_name='heat_trmnt', mysql_length={'eng_char': 191})
    op.create_index(op.f('ix_heat_trmnt_id'), 'heat_trmnt', ['id'], unique=False)
    op.create_index(op.f('ix_kmti_calendar_events_end_date'), 'kmti_calendar_events', ['end_date'], unique=False)
    op.create_index(op.f('ix_kmti_calendar_events_start_date'), 'kmti_calendar_events', ['start_date'], unique=False)
    op.drop_constraint(op.f('fk_cal_user'), 'kmti_calendar_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_cal_todo'), 'kmti_calendar_events', type_='foreignkey')
    op.create_foreign_key(None, 'kmti_calendar_events', 'kmti_todos', ['todo_id'], ['id'])
    op.create_foreign_key(None, 'kmti_calendar_events', 'kmti_users', ['user_id'], ['id'])
    op.alter_column('kmti_chat_messages', 'content',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('kmti_chat_messages', 'reactions',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_lib_hist_sid'), table_name='kmti_librarian_history')
    op.create_index(op.f('ix_kmti_librarian_history_session_id'), 'kmti_librarian_history', ['session_id'], unique=False)
    op.drop_index(op.f('idx_ticket_ip'), table_name='kmti_tickets')
    op.create_index(op.f('ix_kmti_tickets_ip_address'), 'kmti_tickets', ['ip_address'], unique=False)
    op.drop_index(op.f('idx_todo_status'), table_name='kmti_todos')
    op.alter_column('kmti_workstation_status', 'telemetry_data',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('quotation_history', 'data',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('quotations', 'data',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_quotations_workstation'), 'quotations', ['workstation'], unique=False)
    op.alter_column('work_schedule_components', 'is_postponed',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_schedule_components', 'is_postponed',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_quotations_workstation'), table_name='quotations')
    op.alter_column('quotations', 'data',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('quotation_history', 'data',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('kmti_workstation_status', 'telemetry_data',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_todo_status'), 'kmti_todos', ['status'], unique=False)
    op.drop_index(op.f('ix_kmti_tickets_ip_address'), table_name='kmti_tickets')
    op.create_index(op.f('idx_ticket_ip'), 'kmti_tickets', ['ip_address'], unique=False)
    op.drop_index(op.f('ix_kmti_librarian_history_session_id'), table_name='kmti_librarian_history')
    op.create_index(op.f('idx_lib_hist_sid'), 'kmti_librarian_history', ['session_id'], unique=False)
    op.alter_column('kmti_chat_messages', 'reactions',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('kmti_chat_messages', 'content',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_constraint(None, 'kmti_calendar_events', type_='foreignkey')
    op.drop_constraint(None, 'kmti_calendar_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cal_todo'), 'kmti_calendar_events', 'kmti_todos', ['todo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_cal_user'), 'kmti_calendar_events', 'kmti_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_kmti_calendar_events_start_date'), table_name='kmti_calendar_events')
    op.drop_index(op.f('ix_kmti_calendar_events_end_date'), table_name='kmti_calendar_events')
    op.drop_index(op.f('ix_heat_trmnt_id'), table_name='heat_trmnt')
    op.create_index(op.f('idx_ht_eng'), 'heat_trmnt', ['eng_char'], unique=False, mysql_length={'eng_char': 191})
    op.create_index(op.f('idx_ht_category'), 'heat_trmnt', ['category'], unique=False, mysql_length={'category': 191})
    op.alter_column('heat_trmnt', 'jp_char',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               nullable=False)
    op.alter_column('heat_trmnt', 'eng_char',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               nullable=False)
    op.alter_column('heat_trmnt', 'category',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=False)
    op.create_index(op.f('idx_dg_eng'), 'designers', ['english_name'], unique=False)
    op.drop_index(op.f('ix_char_search_id'), table_name='char_search')
    op.create_index(op.f('idx_jp_char'), 'char_search', ['jp_char'], unique=False, mysql_length={'jp_char': 255})
    op.create_index(op.f('idx_eng_char'), 'char_search', ['eng_char'], unique=False, mysql_length={'eng_char': 255})
    op.drop_index(op.f('ix_cad_file_index_parent_path'), table_name='cad_file_index')
    op.drop_index(op.f('ix_cad_file_index_file_path'), table_name='cad_file_index')
    op.create_index(op.f('idx_project_path'), 'cad_file_index', ['project_id', 'file_path'], unique=False, mysql_length={'file_path': 255})
    op.create_index(op.f('idx_project_parent'), 'cad_file_index', ['project_id', 'parent_path'], unique=False, mysql_length={'parent_path': 255})
    op.create_index(op.f('idx_project_folder_type'), 'cad_file_index', ['project_id', 'is_folder', 'file_type'], unique=False)
    op.create_index(op.f('idx_filepath'), 'cad_file_index', ['file_path'], unique=False, mysql_length={'file_path': 255})
    op.create_index(op.f('ft_search'), 'cad_file_index', ['file_name', 'file_path', 'content_text'], unique=False, mysql_prefix='FULLTEXT')
    op.alter_column('cad_file_index', 'content_text',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.create_table('tbl_useracc',
    sa.Column('userId', mysql.INTEGER(display_width=30), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('log_stat', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tblfile',
    sa.Column('Category', mysql.VARCHAR(charset='utf8', length=50), nullable=False),
    sa.Column('Parts_Type', mysql.VARCHAR(charset='utf8', length=80), nullable=False),
    sa.Column('file', mysql.VARCHAR(charset='utf8', length=300), nullable=False),
    sa.Column('dataFile', mysql.MEDIUMBLOB(), nullable=False),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('kmti_feedback',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('workstation', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('message', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('screenshot_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('work_schedule_notifications',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('member_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('job_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('component_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_work_schedule_notifications_member_name'), 'work_schedule_notifications', ['member_name'], unique=False)
    op.create_index(op.f('ix_work_schedule_notifications_job_id'), 'work_schedule_notifications', ['job_id'], unique=False)
    op.create_index(op.f('ix_work_schedule_notifications_id'), 'work_schedule_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_work_schedule_notifications_component_id'), 'work_schedule_notifications', ['component_id'], unique=False)
    op.create_table('kmti_workstation_notes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('workstation_ip', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('author_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_kmti_workstation_notes_workstation_ip'), 'kmti_workstation_notes', ['workstation_ip'], unique=False)
    op.create_table('kmti_user_signatures',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('signature_image', mysql.TEXT(), nullable=False),
    sa.Column('signature_type', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('passcode_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_kmti_user_signatures_name'), 'kmti_user_signatures', ['name'], unique=True)
    op.create_table('tbl_wordchar',
    sa.Column('engWord', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('japWord', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=100), nullable=False),
    sa.PrimaryKeyConstraint('engWord'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('w_account',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('pass', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
